### ISSUE TITLE
exporter fails with error 400

### ISSUE THREAD

**Issue by liyaka** [frodenas/stackdriver_exporter#52]
Running with v0.6.0
My configuration is:

```
stackdriver_exporter:
    container_name: stackdriver_exporter
    image: frodenas/stackdriver-exporter:v0.6.0
    volumes:
      - /data/xxx.json:/tmp/xxx.json
    ports:
      - 9255:9255
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/xxx.json
      - STACKDRIVER_EXPORTER_COLLECTOR_FILL_MISSING_LABEL=true
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=yyy
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES="serviceruntime.googleapis.com"
    restart: always
```

And i keep getting this error:
```
time="2019-05-23T09:42:01Z" level=error msg="Error while getting Google Stackdriver Monitoring metrics: googleapi: Error 400: Field filter had an invalid value of \"metric.type = starts_with(\"\"serviceruntime.googleapis.com\"\")\": Could not parse filter \"metric.type = starts_with(\\\"\\\"serviceruntime.googleapis.com\\\"\\\")\"; syntax error at line 1, column 26, token '\"\"', badRequest" source="monitoring_collector.go:138"
```

what is wrong with my configuration?
